/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/modules/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Roboto", "sans-serif"],
      },
      colors: {
        primary: "var(--primary)",
        bug: 'var(--bug)',
        dark: "var(--dark)", // Grayscale dark
        "dark-type": "var(--dark-type)", // Pokémon type dark
        dragon: "var(--dragon)",
        electric: "var(--electric)",
        fairy: "var(--fairy)",
        fighting: "var(--fighting)",
        fire: "var(--fire)",
        flying: "var(--flying)",
        ghost: "var(--ghost)",
        grass: "var(--grass)",
        ground: "var(--ground)",
        ice: "var(--ice)",
        normal: "var(--normal)",
        poison: "var(--poison)",
        psychic: "var(--psychic)",
        rock: "var(--rock)",
        steel: "var(--steel)",
        water: "var(--water)",
        light: "var(--light)",
        pokeBackground: "var(--pokeBackground)",
        white: "var(--white)",
        medium: "var(--medium)",
      },
      boxShadow: {
        'inner-strong': 'inset 0 0px 4px var(--dark)',
      },
    },
  },
  safelist: [
    'bg-bug',
    'bg-dark',
    'bg-dragon',
    'bg-electric',
    'bg-fairy',
    'bg-fighting',
    'bg-fire',
    'bg-flying',
    'bg-ghost',
    'bg-grass',
    'bg-ground',
    'bg-ice',
    'bg-normal',
    'bg-poison',
    'bg-psychic',
    'bg-rock',
    'bg-steel',
    'bg-water',
    'bg-medium',
    'bg-light',
    'bg-pokeBackground',
    'bg-white',
    'text-primary',
    'text-dark',
    'text-dark-type',
    'text-bug',
    'text-dragon',
    'text-electric',
    'text-fairy',
    'text-fighting',
    'text-fire',
    'text-flying',
    'text-ghost',
    'text-grass',
    'text-ground',
    'text-ice',
    'text-normal',
    'text-poison',
    'text-psychic',
    'text-rock',
    'text-steel',
    'text-water',
    'text-medium',
    'text-light',
    'text-pokeBackground',
    'text-white',,
    'border-bug',
    'border-dark',
    'border-dragon',
    'border-electric',
    'border-fairy',
    'border-fighting',
    'border-fire',
    'border-flying',
    'border-ghost',
    'border-grass',
    'border-ground',
    'border-ice',
    'border-normal',
    'border-poison',
    'border-psychic',
    'border-rock',
    'border-steel',
    'border-water',
    'border-medium',
    'border-light',
    'border-pokeBackground',
    'border-white',
  ],
  plugins: [],
};
